### ISSUE TITLE
Module build failed. Error: ./~/radium-grid/lib/index.js

### ISSUE THREAD

**Issue by maotora** [FormidableLabs/radium-grid#71]
Hi, nice component u got here.

I'm facing this error just after installing radium-grid with
`npm install --save radium-grid` and 
`import {Grid, Cell} from 'radium-grid';` in my react file.
 When i run my task i get the error 

``` bash
 Error: ./~/radium-grid/lib/index.js
Module build failed: Error: [BABEL] /home/niggacode/Projects/Sites/kombo/node_modules/radium-grid/lib/index.js: Couldn't resolve extends clause of ./node_modules/builder-radium-component/config/babel/.babelrc in /home/niggacode/Projects/Sites/kombo/node_modules/radium-grid/.babelrc
    at Logger.error (/home/niggacode/Projects/Sites/kombo/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at ConfigChainBuilder.mergeConfig (/home/niggacode/Projects/Sites/kombo/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:190:32)
    at ConfigChainBuilder.addConfig (/home/niggacode/Projects/Sites/kombo/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:161:10)
    at ConfigChainBuilder.findConfigs (/home/niggacode/Projects/Sites/kombo/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:100:16)
    at buildConfigChain (/home/niggacode/Projects/Sites/kombo/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:65:13)
    at OptionManager.init (/home/niggacode/Projects/Sites/kombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:359:58)
    at File.initOptions (/home/niggacode/Projects/Sites/kombo/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/home/niggacode/Projects/Sites/kombo/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/home/niggacode/Projects/Sites/kombo/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/niggacode/Projects/Sites/kombo/node_modules/babel-loader/index.js:38:20)
 @ ./assets/jsx/main.js 22:18-40
```

I'm not sure what i am doing wrong, please help.

**Comment by tptee** [comment]
Can you try `v2.0.3` to see if that fixes your issue?

**Comment by maotora** [comment]
@tptee Hi, thanks for your reply.

I'm uisng `radium-grid: ^2.0.3` & `radium: ^0.18.1` in my package.json _both saved as dependencies_ (not devDependencies).

The problem starts when I `import { Grid, Cell } from "radium-grid";` even before i start using the components.

[Here](https://github.com/maotora/gulp-react-css-modules-boilerplate/blob/radium-grid/assets/jsx/components/home/header/nav.js) my project maybe you can take a look at it.

Thanks!

**Comment by maotora** [comment]
The patch above is a joke of a commit i didn't know will reflect to this post.
Anyway, I *fixed* the problem with my [patched-radium-grid](https://github.com/maotora/radium-grid).

1. I basically removed the `extends` clause in [.babelrc](https://github.com/FormidableLabs/radium-grid/blob/master/.babelrc) then installed and added [everything](https://github.com/FormidableLabs/builder-radium-component/blob/master/config/babel/.babelrc) it was extending in the [patched-radium-grid](https://github.com/maotora/radium-grid).
2. Then added some needed babel plugins in my project _not radim-grid_ structure.

Hope to see this fixed in `radim/radium-grid` or i'm given a more appropriate way that i'm missing in using this component.

Thanks.

**Comment by ryan-roemer** [comment]
The issue is that the babelrc shouldn't be being read in the first place as package.json:main points to already built lib/index.js

@maotora - are you piping radium-grid to a Babel loader somehow? (Or if you're doing a react native project this will likely be automatically that case)

Anyhoo, @tptee we can easily fix this with switching to the publishr workflow that victory just did with swapping builder + builder-radium-component to devdeps and adding an .npmignore.publishr to _remove_ the .babelrc from publication.

Also minor nit - we currently have duplicate builder deps in prod and dev deps.

Thanks!

**Comment by ryan-roemer** [comment]
@tptee - see https://github.com/FormidableLabs/victory/issues/416 for what we did in victory...

**Comment by maotora** [comment]
DAng! Thanks @ryan-roemer :+1: 

hehe.. In my `webpack` task i was passing all js files into babel loader!
_Not a very experienced webpack user._ But I've seen `exclude: /node_modules/` and ignored it for sometime and today it proved it's point!

Thanks!
